### ISSUE TITLE
change presentation of feedback for comparison conditions

### ISSUE THREAD

**Issue by scottbateman** [ncphillips/crowdstudy_pointing_task#4]
This issue has four parts:

1) remove comparison data for first two rounds
-for the comparison conditions let's remove the comparison data after rounds 1 and 2.
-this means that after rounds 1 and 2 they should only get the non-comparison condition questions
-this is to reduce time and allow us to better see an influence from comparison data

2) for comparison conditions use feedback that comes from the no comparison condition only, not from the other conditions

3) show comparison feedback data for the current round only (will only be relevant for real data condition, see part 4)
-this means in the comparison conditions show data that is for the current round only. 
-e.g., The comparison data for after round 1, should be the no comparison condition data for round 1 only, 
-The data for after round 2, should be the no comparison condition data for round 2 only, etc.

4) fake data should be calculated based on the current user's round data using the following calculations
-fake user is worse: expert user is 10% worse then the user, average user is 25% worse
-fake user is better: expert user is 25% better than the user, average is 10% better

-let's make sure that the calculations actually show a difference though, so if it takes me .8 seconds per target (average better user would only be 10% better or .08 secs. better) this won't show up, so let's round up to the smallest unit we are displaying (for the example: .1 sec;. so the better avg user would be at .7 seconds).

**Comment by ncphillips** [comment]
Done
